version: '3.9'

services:
  contact-app:
    build:
       context: ./contact-backend
    network_mode: host
    depends_on:
      - mongodb   
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27019:27017'
    volumes:
      - dbdata6:/data/db
    networks:
        - internal_network
    restart: always
networks:
  internal_network:
    driver: bridge
volumes:
  dbdata6: